name: BountyPlus
version: '1.0'
description: "Place bounties/hits on other players"
main: net.wispwood.bounty.Bounty
api-version: '1.21'
author: "Aduhkiss"
depend: ["Vault"]
commands:
  bounty:
    permission: bounty.bounty
  bountyreload:
    description: Reload the configuration and messages
    permission: bounty.bountyreload
permissions:
  bounty.bounty:
    default: true
  bounty.bountyreload:
    default: op